# This is a workflow used for automated build on Windows platform
name: build-windows

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Uncomment the line below to disable the build job
    #if: ${{ false }}
    runs-on: windows-latest    
    steps:
      - run: git config --global core.autocrlf false

      - name: Checkout esp-tools repository
        uses: actions/checkout@v4

      - name: Checkout ESP-IDF v5.4 repository with submodules recursively
        uses: actions/checkout@v4
        with:
          repository: espressif/esp-idf
          ref: v5.4
          submodules: recursive
          path: esp-idf
 
      - name: Cache the tools
        uses: actions/cache@v4
        with:
          path: windows
          key: ${{ runner.os }}-esp-tools
      - name: Install the tools for Windows platform if not cached
        shell: cmd
        run: |
          dir
          if not exist windows ( scripts\get-tools.cmd )
 
      - name: Get ESP-IDF version
        shell: cmd
        run: scripts\test.cmd version

      - name: Build ESP-IDF blink example
        shell: cmd
        run: scripts\test.cmd build
